version:  '3.7'

services:
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbtest
    ports:
      - 3306:3306
    networks:
      - net
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - 8900:80
    depends_on:
      - php
    links:
      - php:php
    networks:
      - net
  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000
    volumes:
      - './:/usr/src/app'
    networks:
      - net
networks:
  net:

